<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gz_example_robot">

<xacro:property name="chassis_width"    value="0.16" />
<xacro:property name="chassis_length"   value="0.24" />
<xacro:property name="chassis_height"   value="0.12" />
<xacro:property name="wheel_separation" value="0.20" />
<xacro:property name="wheel_radius"     value="0.08" />
<xacro:property name="wheel_offset"     value="${wheel_radius/4}" />
<xacro:property name="wheel_width"      value="0.04" />
<xacro:property name="sphere_radius"    value="${wheel_radius+wheel_offset-(chassis_height/2)}" />
<xacro:property name="base_offset"      value="0.08" />
<xacro:property name="footprint_z"      value="${chassis_height/2 + sphere_radius}" />

  <!-- LINKS -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${base_offset} 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${base_offset} 0 0"/>
    </collision>

    <inertial>
      <mass value="10"/>
      <inertia ixx="0.0033" ixy="0.0" ixz="0.0" iyy="0.006" iyz="0.0" izz="0.007"/>
    </inertial>
  </link>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
        <color rgba="0.1 0.1 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.0032"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
        <color rgba="0.1 0.1 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.0032"/>
    </inertial>
  </link>

  <link name="front_wheel">
    <visual>
      <geometry>
        <sphere radius="${sphere_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
        <color rgba="0.1 0.1 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${sphere_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00016" ixy="0.0" ixz="0.0" iyy="0.00016" iyz="0.0" izz="0.00016"/>
    </inertial>
  </link>

  <link name="chassis_link">
  <!-- Convenient place to reference sensors to -->
  </link>

  <link name="imu_link">
  <!-- Frame to attach an IMU to -->
  </link> 

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder length="0.03" radius="0.03" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 -0.005"/>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="0.03" radius="0.03" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 -0.005"/>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.00045"/>
    </inertial>
  </link>


  <!-- JOINTS -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="${base_offset} 0 ${footprint_z}" rpy="0 0 0"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} -${wheel_offset}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_separation/2} -${wheel_offset}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="front_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_wheel"/>
    <origin xyz="${base_offset + (chassis_length/2) - sphere_radius} 0 -${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="${base_offset} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="lidar_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.1 0 0.02" rpy="0 0 0"/>
  </joint>


  <!-- GAZEBO PLUGINS -->
  <gazebo>
    <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
      <!-- wheels -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.16</wheel_separation>
      <wheel_diameter>0.16</wheel_diameter>

      <!-- limits -->	
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_odom_tf>false</publish_odom_tf>
      
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      <topic>/model/gz_example_robot/cmd_vel</topic>
      <odom_topic>/model/gz_example_robot/odometry</odom_topic>
    </plugin>
  </gazebo>

 
</robot>